openapi: 3.0.0
info:
  title: Hacienda Montecristo APIs
  description: Documentación de APIs del Back end del proyecto de la Hacienda Montecristo
  version: 1.0.15

servers:
  - url: http://localhost:3000
    description: Local development server

paths:
  /api/users/get:
    $ref: "./paths/getAllUsers.yaml"
  /api/users/get/:{username}:
    $ref: "./paths/getByUsername.yaml"
  /api/users/create:
    $ref: "./paths/createUser.yaml"
  /api/users/update/:{username}:
    $ref: "./paths/updateUserbyUsername.yaml"
  /api/invoices/create:
    $ref: "./paths/invoices.yaml#/createInvoice"
  /api/invoices/get:
    $ref: "./paths/invoices.yaml#/getAllInvoices"
  /api/invoices/get/{invoiceID}:
    $ref: "./paths/invoices.yaml#/getInvoiceByID"
  /api/invoice-details/create:
    $ref: "./paths/invoices.yaml#/createInvoiceDetail"
  /api/invoice-details/get/{invoiceID}:
    $ref: "./paths/invoices.yaml#/getInvoiceDetailsByInvoiceID"
  /api/invoice-details/delete/{invoiceDetailID}:
    $ref: "./paths/invoices.yaml#/deleteInvoiceDetail"