openapi: 3.0.0
info:
  title: Hacienda Montecristo APIs
  description: Documentación de APIs del Back end del proyecto de la Hacienda Montecristo
  version: 1.0.15

servers:
  - url: http://localhost:3000/
    description: Local development server

paths:
  /api/users/get:
    $ref: "./paths/getAllUsers.yaml"
  /api/users/get/:{username}:
    $ref: "./paths/getByUsername.yaml"
  /api/users/create:
    $ref: "./paths/createUser.yaml"
  /api/users/update/:{username}:
    $ref: "./paths/updateUserbyUsername.yaml"
  /api/invoices/create:
    $ref: "./paths/createInvoice.yaml"
  /api/invoices/get:
    $ref: "./paths/getAllInvoices.yaml"
  /api/invoices/get/{invoiceID}:
    $ref: "./paths/getInvoiceByID.yaml"
  /api/invoice-details/create:
    $ref: "./paths/createInvoiceDetail.yaml"
  /api/invoice-details/get/{invoiceID}:
    $ref: "./paths/getInvoiceDetailsByInvoiceID.yaml"
  /api/invoice-details/delete/{invoiceDetailID}:
    $ref: "./paths/deleteInvoiceDetail.yaml"